# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'preferencesGui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(467, 717)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(60, 640, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(30, 30, 371, 591))
        self.tabWidget.setObjectName("tabWidget")
        self.General = QtWidgets.QWidget()
        self.General.setObjectName("General")
        self.frame = QtWidgets.QFrame(self.General)
        self.frame.setGeometry(QtCore.QRect(10, 40, 351, 141))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.doSetPhotoPath = QtWidgets.QPushButton(self.frame)
        self.doSetPhotoPath.setGeometry(QtCore.QRect(10, 10, 99, 30))
        self.doSetPhotoPath.setStyleSheet("font: 11pt \"PibotoLt\";")
        self.doSetPhotoPath.setObjectName("doSetPhotoPath")
        self.doSetVideoPath = QtWidgets.QPushButton(self.frame)
        self.doSetVideoPath.setGeometry(QtCore.QRect(10, 50, 99, 30))
        self.doSetVideoPath.setStyleSheet("font: 11pt \"PibotoLt\";")
        self.doSetVideoPath.setObjectName("doSetVideoPath")
        self.doSetFilePath = QtWidgets.QPushButton(self.frame)
        self.doSetFilePath.setGeometry(QtCore.QRect(10, 90, 99, 30))
        self.doSetFilePath.setStyleSheet("font: 11pt \"PibotoLt\";")
        self.doSetFilePath.setObjectName("doSetFilePath")
        self.defaultPhotoPath = QtWidgets.QLabel(self.frame)
        self.defaultPhotoPath.setGeometry(QtCore.QRect(140, 10, 161, 22))
        self.defaultPhotoPath.setStyleSheet("color : blue")
        self.defaultPhotoPath.setObjectName("defaultPhotoPath")
        self.defaultVideoPath = QtWidgets.QLabel(self.frame)
        self.defaultVideoPath.setGeometry(QtCore.QRect(140, 50, 181, 22))
        self.defaultVideoPath.setStyleSheet("color : blue")
        self.defaultVideoPath.setObjectName("defaultVideoPath")
        self.defaultFilePath = QtWidgets.QLabel(self.frame)
        self.defaultFilePath.setGeometry(QtCore.QRect(140, 100, 181, 22))
        self.defaultFilePath.setStyleSheet("color : blue")
        self.defaultFilePath.setObjectName("defaultFilePath")
        self.label = QtWidgets.QLabel(self.General)
        self.label.setGeometry(QtCore.QRect(10, 10, 161, 22))
        self.label.setObjectName("label")
        self.frame_2 = QtWidgets.QFrame(self.General)
        self.frame_2.setGeometry(QtCore.QRect(10, 210, 351, 101))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 151, 22))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(10, 50, 151, 22))
        self.label_4.setObjectName("label_4")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_4.setGeometry(QtCore.QRect(268, 10, 71, 30))
        self.pushButton_4.setStyleSheet("font: 75 italic 10pt \"PibotoLt\";\n"
"font: 11pt \"PibotoLt\";")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_5.setGeometry(QtCore.QRect(268, 50, 71, 30))
        self.pushButton_5.setStyleSheet("font: 11pt \"PibotoLt\";")
        self.pushButton_5.setObjectName("pushButton_5")
        self.comboBox = QtWidgets.QComboBox(self.frame_2)
        self.comboBox.setGeometry(QtCore.QRect(170, 10, 83, 32))
        self.comboBox.setObjectName("comboBox")
        self.comboBox_2 = QtWidgets.QComboBox(self.frame_2)
        self.comboBox_2.setGeometry(QtCore.QRect(170, 50, 83, 32))
        self.comboBox_2.setObjectName("comboBox_2")
        self.frame_3 = QtWidgets.QFrame(self.General)
        self.frame_3.setGeometry(QtCore.QRect(10, 350, 351, 161))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_6 = QtWidgets.QLabel(self.frame_3)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 131, 22))
        self.label_6.setObjectName("label_6")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_6.setGeometry(QtCore.QRect(308, 10, 31, 30))
        self.pushButton_6.setStyleSheet("font: 75 11pt \"PibotoLt\";\n"
"font: 75 11pt \"PibotoLt\";")
        self.pushButton_6.setObjectName("pushButton_6")
        self.checkBox = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox.setGeometry(QtCore.QRect(20, 80, 271, 27))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox_2.setGeometry(QtCore.QRect(20, 110, 261, 27))
        self.checkBox_2.setObjectName("checkBox_2")
        self.label_7 = QtWidgets.QLabel(self.frame_3)
        self.label_7.setGeometry(QtCore.QRect(10, 50, 141, 22))
        self.label_7.setObjectName("label_7")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit.setGeometry(QtCore.QRect(140, 10, 161, 32))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.General)
        self.label_2.setGeometry(QtCore.QRect(10, 180, 241, 22))
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.General)
        self.label_5.setGeometry(QtCore.QRect(10, 320, 68, 22))
        self.label_5.setObjectName("label_5")
        self.tabWidget.addTab(self.General, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        self.doSetPhotoPath.clicked.connect(Dialog.setDefaultPhotoPath)
        self.doSetVideoPath.clicked.connect(Dialog.setDefaultVideoPath)
        self.doSetFilePath.clicked.connect(Dialog.setDefaultFilePath)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.doSetPhotoPath.setText(_translate("Dialog", "Photos"))
        self.doSetVideoPath.setText(_translate("Dialog", "Videos"))
        self.doSetFilePath.setText(_translate("Dialog", "Files"))
        self.defaultPhotoPath.setText(_translate("Dialog", "/home/pi/Pictures"))
        self.defaultVideoPath.setText(_translate("Dialog", "/home/pi/Videos"))
        self.defaultFilePath.setText(_translate("Dialog", "/home/pi/Documents"))
        self.label.setText(_translate("Dialog", "Set default directories "))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">Photo capture format</span></p></body></html>"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">Video capture format</span></p></body></html>"))
        self.pushButton_4.setText(_translate("Dialog", "parms..."))
        self.pushButton_5.setText(_translate("Dialog", "parms..."))
        self.label_6.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">Timestamp format</span></p></body></html>"))
        self.pushButton_6.setText(_translate("Dialog", "?"))
        self.checkBox.setText(_translate("Dialog", "Include timestamp in photo name"))
        self.checkBox_2.setText(_translate("Dialog", "Include timestamp in video name"))
        self.label_7.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">Sample timestamp:</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "Photo/Video capture formats"))
        self.label_5.setText(_translate("Dialog", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.General), _translate("Dialog", "&General"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "&Interface"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "&Other"))

