# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zoomTabGui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(822, 710)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.getXOrigin = KeyboardSlider(self.centralwidget)
        self.getXOrigin.setGeometry(QtCore.QRect(30, 500, 741, 26))
        self.getXOrigin.setMaximum(4056)
        self.getXOrigin.setOrientation(QtCore.Qt.Horizontal)
        self.getXOrigin.setObjectName("getXOrigin")
        self.getYOrigin = KeyboardSlider(self.centralwidget)
        self.getYOrigin.setGeometry(QtCore.QRect(40, 20, 26, 451))
        self.getYOrigin.setMaximum(3040)
        self.getYOrigin.setOrientation(QtCore.Qt.Vertical)
        self.getYOrigin.setObjectName("getYOrigin")
        self.getZoom = KeyboardSlider(self.centralwidget)
        self.getZoom.setGeometry(QtCore.QRect(730, 20, 26, 461))
        self.getZoom.setMinimum(1920)
        self.getZoom.setMaximum(3470)
        self.getZoom.setProperty("value", 3470)
        self.getZoom.setOrientation(QtCore.Qt.Vertical)
        self.getZoom.setObjectName("getZoom")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 480, 91, 22))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 0, 101, 22))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(670, 0, 91, 22))
        self.label_3.setObjectName("label_3")
        self.showPreview = QtWidgets.QCheckBox(self.centralwidget)
        self.showPreview.setGeometry(QtCore.QRect(490, 570, 161, 27))
        self.showPreview.setObjectName("showPreview")
        self.doQuit = QtWidgets.QPushButton(self.centralwidget)
        self.doQuit.setGeometry(QtCore.QRect(70, 520, 99, 30))
        self.doQuit.setObjectName("doQuit")
        self.snap = QtWidgets.QPushButton(self.centralwidget)
        self.snap.setGeometry(QtCore.QRect(60, 570, 99, 30))
        self.snap.setObjectName("snap")
        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setGeometry(QtCore.QRect(360, 530, 71, 30))
        self.start.setObjectName("start")
        self.end = QtWidgets.QPushButton(self.centralwidget)
        self.end.setGeometry(QtCore.QRect(360, 570, 71, 30))
        self.end.setObjectName("end")
        self.runZoom = QtWidgets.QPushButton(self.centralwidget)
        self.runZoom.setGeometry(QtCore.QRect(350, 610, 99, 30))
        self.runZoom.setObjectName("runZoom")
        self.diag = QtWidgets.QPushButton(self.centralwidget)
        self.diag.setGeometry(QtCore.QRect(60, 610, 99, 30))
        self.diag.setObjectName("diag")
        self.showStart = QtWidgets.QPushButton(self.centralwidget)
        self.showStart.setGeometry(QtCore.QRect(240, 530, 81, 30))
        self.showStart.setObjectName("showStart")
        self.showEnd = QtWidgets.QPushButton(self.centralwidget)
        self.showEnd.setGeometry(QtCore.QRect(230, 580, 81, 30))
        self.showEnd.setObjectName("showEnd")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(110, 60, 507, 380))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.adjustZoom = DragButton(self.frame)
        self.adjustZoom.setGeometry(QtCore.QRect(190, 250, 22, 22))
        self.adjustZoom.setObjectName("adjustZoom")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 822, 28))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.getXOrigin.valueChanged['int'].connect(MainWindow.setXOrigin)
        self.getZoom.valueChanged['int'].connect(MainWindow.setZoom)
        self.getYOrigin.valueChanged['int'].connect(MainWindow.setYOrigin)
        self.doQuit.clicked.connect(MainWindow.doQuit)
        self.showPreview.clicked['bool'].connect(MainWindow.showPreview)
        self.snap.clicked.connect(MainWindow.doSnap)
        self.start.clicked.connect(MainWindow.doSetStart)
        self.end.clicked.connect(MainWindow.doSetEnd)
        self.runZoom.clicked.connect(MainWindow.doRunZoom)
        self.diag.clicked.connect(MainWindow.printDiag)
        self.showStart.clicked.connect(MainWindow.doShowStart)
        self.showEnd.clicked.connect(MainWindow.doShowEnd)
        self.adjustZoom.posChanged['int','int'].connect(MainWindow.setZoomWithButton)
        self.adjustZoom.released.connect(MainWindow.movePosition)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "set x origin"))
        self.label_2.setText(_translate("MainWindow", "set y origin"))
        self.label_3.setText(_translate("MainWindow", "zoom"))
        self.showPreview.setText(_translate("MainWindow", "show preview"))
        self.doQuit.setText(_translate("MainWindow", "quit"))
        self.snap.setText(_translate("MainWindow", "snap!"))
        self.start.setText(_translate("MainWindow", "set start"))
        self.end.setText(_translate("MainWindow", "set end"))
        self.runZoom.setText(_translate("MainWindow", "run zoom"))
        self.diag.setText(_translate("MainWindow", "diag"))
        self.showStart.setText(_translate("MainWindow", "show start"))
        self.showEnd.setText(_translate("MainWindow", "show end"))
        self.adjustZoom.setText(_translate("MainWindow", "b"))

from dragbutton import DragButton
from zoomTab import KeyboardSlider
