# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'shooterGui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(851, 889)
        self.captureTab = QtWidgets.QTabWidget(Form)
        self.captureTab.setGeometry(QtCore.QRect(240, 650, 801, 221))
        self.captureTab.setInputMethodHints(QtCore.Qt.ImhUrlCharactersOnly)
        self.captureTab.setObjectName("captureTab")
        self.still = QtWidgets.QWidget()
        self.still.setObjectName("still")
        self.snapSave = QtWidgets.QPushButton(self.still)
        self.snapSave.setGeometry(QtCore.QRect(20, 20, 99, 30))
        self.snapSave.setObjectName("snapSave")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.still)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(270, 20, 160, 34))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_15 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_15.setObjectName("label_15")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.stillFileRoot = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.stillFileRoot.setInputMethodHints(QtCore.Qt.ImhNone)
        self.stillFileRoot.setObjectName("stillFileRoot")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.stillFileRoot)
        self.acceptStillRootUpdate = QtWidgets.QPushButton(self.still)
        self.acceptStillRootUpdate.setGeometry(QtCore.QRect(440, 20, 61, 30))
        self.acceptStillRootUpdate.setObjectName("acceptStillRootUpdate")
        self.captureTab.addTab(self.still, "")
        self.video = QtWidgets.QWidget()
        self.video.setObjectName("video")
        self.vidPosSlider = QtWidgets.QSlider(self.video)
        self.vidPosSlider.setGeometry(QtCore.QRect(220, 30, 571, 26))
        self.vidPosSlider.setMaximum(1000)
        self.vidPosSlider.setOrientation(QtCore.Qt.Horizontal)
        self.vidPosSlider.setObjectName("vidPosSlider")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.video)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 196, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.startRecordVid = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.startRecordVid.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/media-record.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startRecordVid.setIcon(icon)
        self.startRecordVid.setObjectName("startRecordVid")
        self.horizontalLayout_2.addWidget(self.startRecordVid)
        self.playVid = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.playVid.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/media-playback-start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playVid.setIcon(icon1)
        self.playVid.setObjectName("playVid")
        self.horizontalLayout_2.addWidget(self.playVid)
        self.stopVid = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.stopVid.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/media-playback-stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopVid.setIcon(icon2)
        self.stopVid.setObjectName("stopVid")
        self.horizontalLayout_2.addWidget(self.stopVid)
        self.pauseVid = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pauseVid.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/media-playback-pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pauseVid.setIcon(icon3)
        self.pauseVid.setObjectName("pauseVid")
        self.horizontalLayout_2.addWidget(self.pauseVid)
        self.useZoomOnRecord = QtWidgets.QCheckBox(self.video)
        self.useZoomOnRecord.setGeometry(QtCore.QRect(10, 70, 181, 27))
        self.useZoomOnRecord.setObjectName("useZoomOnRecord")
        self.videoStabilization = QtWidgets.QCheckBox(self.video)
        self.videoStabilization.setGeometry(QtCore.QRect(10, 130, 171, 27))
        self.videoStabilization.setObjectName("videoStabilization")
        self.frameRate = QtWidgets.QComboBox(self.video)
        self.frameRate.setGeometry(QtCore.QRect(340, 90, 83, 32))
        self.frameRate.setObjectName("frameRate")
        self.frameRate.addItem("")
        self.frameRate.addItem("")
        self.frameRate.addItem("")
        self.frameRate.addItem("")
        self.frameRateLabel = QtWidgets.QLabel(self.video)
        self.frameRateLabel.setGeometry(QtCore.QRect(240, 90, 91, 22))
        self.frameRateLabel.setObjectName("frameRateLabel")
        self.formLayoutWidget = QtWidgets.QWidget(self.video)
        self.formLayoutWidget.setGeometry(QtCore.QRect(440, 90, 160, 41))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.videoFileRoot = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.videoFileRoot.setInputMethodHints(QtCore.Qt.ImhNone)
        self.videoFileRoot.setObjectName("videoFileRoot")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.videoFileRoot)
        self.acceptVideoRootUpdate = QtWidgets.QPushButton(self.video)
        self.acceptVideoRootUpdate.setGeometry(QtCore.QRect(610, 90, 61, 30))
        self.acceptVideoRootUpdate.setObjectName("acceptVideoRootUpdate")
        self.endRecWhenZoomEnds = QtWidgets.QCheckBox(self.video)
        self.endRecWhenZoomEnds.setGeometry(QtCore.QRect(10, 100, 231, 27))
        self.endRecWhenZoomEnds.setObjectName("endRecWhenZoomEnds")
        self.captureTab.addTab(self.video, "")
        self.thumbnails = QtWidgets.QListWidget(Form)
        self.thumbnails.setGeometry(QtCore.QRect(20, 10, 140, 601))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.thumbnails.setFont(font)
        self.thumbnails.setIconSize(QtCore.QSize(128, 96))
        self.thumbnails.setViewMode(QtWidgets.QListView.IconMode)
        self.thumbnails.setWordWrap(True)
        self.thumbnails.setObjectName("thumbnails")
        self.resizePreview = QtWidgets.QSlider(Form)
        self.resizePreview.setGeometry(QtCore.QRect(360, 620, 591, 26))
        self.resizePreview.setOrientation(QtCore.Qt.Horizontal)
        self.resizePreview.setObjectName("resizePreview")
        self.previewVisible = QtWidgets.QCheckBox(Form)
        self.previewVisible.setGeometry(QtCore.QRect(260, 620, 91, 27))
        self.previewVisible.setObjectName("previewVisible")
        self.imgContainer = QtWidgets.QLabel(Form)
        self.imgContainer.setGeometry(QtCore.QRect(190, 10, 800, 600))
        self.imgContainer.setFrameShape(QtWidgets.QFrame.Box)
        self.imgContainer.setText("")
        self.imgContainer.setObjectName("imgContainer")
        self.isDatestamp = QtWidgets.QRadioButton(Form)
        self.isDatestamp.setGeometry(QtCore.QRect(20, 820, 119, 27))
        self.isDatestamp.setObjectName("isDatestamp")
        self.isCounter = QtWidgets.QRadioButton(Form)
        self.isCounter.setGeometry(QtCore.QRect(20, 850, 119, 27))
        self.isCounter.setChecked(True)
        self.isCounter.setObjectName("isCounter")
        self.clearImgContainer = QtWidgets.QPushButton(Form)
        self.clearImgContainer.setGeometry(QtCore.QRect(110, 620, 21, 20))
        self.clearImgContainer.setObjectName("clearImgContainer")
        self.showOverlay = QtWidgets.QCheckBox(Form)
        self.showOverlay.setGeometry(QtCore.QRect(160, 620, 101, 27))
        self.showOverlay.setObjectName("showOverlay")

        self.retranslateUi(Form)
        self.captureTab.setCurrentIndex(1)
        self.thumbnails.itemDoubleClicked['QListWidgetItem*'].connect(Form.doThumbnailClicked)
        self.stopVid.clicked.connect(Form.doStopVid)
        self.startRecordVid.clicked.connect(Form.doRecordVid)
        self.resizePreview.valueChanged['int'].connect(Form.setPreviewSize)
        self.vidPosSlider.sliderMoved['int'].connect(Form.setPosition)
        self.snapSave.clicked.connect(Form.snapAndSave)
        self.previewVisible.clicked.connect(Form.showPreview)
        self.playVid.clicked.connect(Form.doPlayVid)
        self.pauseVid.clicked.connect(Form.doPauseVid)
        self.isDatestamp.clicked.connect(Form.setFileNameFormat)
        self.isCounter.clicked.connect(Form.setFileNameFormat)
        self.stillFileRoot.textChanged['QString'].connect(Form.setFileRoot)
        self.captureTab.currentChanged['int'].connect(Form.setCaptureMode)
        self.useZoomOnRecord.clicked['bool'].connect(Form.setRecordZoomFlag)
        self.videoStabilization.clicked['bool'].connect(Form.doVideoStabilization)
        self.frameRate.currentIndexChanged['QString'].connect(Form.setFrameRate)
        self.acceptStillRootUpdate.clicked.connect(Form.updateStillRoot)
        self.acceptVideoRootUpdate.clicked.connect(Form.updateVideoRoot)
        self.clearImgContainer.clicked.connect(Form.doClearImgContainer)
        self.showOverlay.clicked['bool'].connect(Form.doShowOverlay)
        self.endRecWhenZoomEnds.clicked['bool'].connect(Form.endRecWithZoom)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.snapSave.setText(_translate("Form", "Snap/Save"))
        self.label_15.setText(_translate("Form", "File root"))
        self.stillFileRoot.setText(_translate("Form", "img_"))
        self.acceptStillRootUpdate.setText(_translate("Form", "Update"))
        self.captureTab.setTabText(self.captureTab.indexOf(self.still), _translate("Form", "Still"))
        self.useZoomOnRecord.setText(_translate("Form", "Use Zoom on Record"))
        self.videoStabilization.setText(_translate("Form", "Video Stabilization"))
        self.frameRate.setItemText(0, _translate("Form", "25"))
        self.frameRate.setItemText(1, _translate("Form", "30"))
        self.frameRate.setItemText(2, _translate("Form", "35"))
        self.frameRate.setItemText(3, _translate("Form", "40"))
        self.frameRateLabel.setText(_translate("Form", "Frame Rate"))
        self.label.setText(_translate("Form", "File Root"))
        self.videoFileRoot.setText(_translate("Form", "img_"))
        self.acceptVideoRootUpdate.setText(_translate("Form", "Update"))
        self.endRecWhenZoomEnds.setText(_translate("Form", "End record when Zoom ends"))
        self.captureTab.setTabText(self.captureTab.indexOf(self.video), _translate("Form", "Video"))
        self.previewVisible.setText(_translate("Form", "Preview"))
        self.isDatestamp.setText(_translate("Form", "Datestamp"))
        self.isCounter.setText(_translate("Form", "Counter "))
        self.clearImgContainer.setText(_translate("Form", "c"))
        self.showOverlay.setText(_translate("Form", "overlay"))

import resource_rc
